export enum GameStatus {
  AwaitingStart = 0,
  Shuffle = 1,
  Deal = 2,
  DrawPrivateCards = 3,
  BetPreFlop = 4,
  DrawFlop = 5,
  BetFlop = 6,
  DrawTurn = 7,
  BetTurn = 8,
  DrawRiver = 9,
  BetRiver = 10,
  ShowDown = 11,
  PotDistribution = 12,
}
