[package]
name = "ZKDeck"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
aptos_std = "0x1"
std = "0x1"
zk_deck = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
