name: cicd

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  deployments: write
  issues: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run Checks
        uses: ./.github/actions/check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run Tests
        uses: ./.github/actions/test

  deploy:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Deploy App
        id: deploy
        uses: ./.github/actions/deploy
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          piesocket-api-key: ${{ secrets.PIESOCKET_API_KEY }}
      - name: Comment Preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Preview URL: ${{ steps.deploy.outputs.cloudflare-preview-url }}"
            })
