name: cicd

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run Checks
        uses: ./.github/actions/check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run Tests
        uses: ./.github/actions/test

  deploy:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Deploy App
        id: deploy
        uses: ./.github/actions/deploy
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Publish Preview URL
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "**Preview URL**: [${{ steps.deploy.outputs.cloudflare-preview-url }}](${{ steps.deploy.outputs.cloudflare-preview-url }})"
